Keith dev
michaelc445/street-fighter-pygame pull request #38
Opened 2023-02-23 13:18 UTC by mwaloszek55

2023-02-23 13:49 UTC, michaelc445 commented on game/characters/nomad.py
> +                                    self.rect.height // 2, damage, knockback, self, 10 - (20 * self.flip), tornado))
is this loading the projectile image from disk each time one is created?

2023-02-23 13:53 UTC, michaelc445 requested changes

2023-02-23 13:53 UTC, michaelc445 commented on game/characters/wizard.py
> +                                self.rect.height // 2, damage, knockback, self, 10 - (20 * self.flip), pulse))
same here, we should probably just load the images once and pass the scaled version to the projectile constructor

2023-02-23 13:53 UTC, michaelc445 commented on game/characters/wizard.py
> +                                self.rect.height, damage, knockback, self, 5 - (10 * self.flip), orbSpell))
same here

2023-02-23 13:53 UTC, michaelc445 commented on game/fighter.py
> +        return animationList#
animationList# ?

2023-02-24 15:42 UTC, Konrad-Dagiel commented
Works for me

2023-02-24 15:44 UTC, michaelc445 approved these changes

2023-02-24 16:03 UTC, Konrad-Dagiel approved these changes
works for me nice

2023-02-24 16:05 UTC, merged